[project]
name = "sim-wrappers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Marc Toussaint", email = "toussaint@tu-berlin.de" }
]
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.2.2",
    "gymnasium-robotics>=1.4.1",
    "mujoco>=3.3.7",
    "robotic>=0.3.4",
]

[project.scripts]
sim-wrappers = "sim_wrappers:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
